// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXaJkK6lxmGuy2G6iaR-n0LbdaT7Jt2l0',
    appId: '1:91000484395:web:cb896757b53fb5dc35b06e',
    messagingSenderId: '91000484395',
    projectId: 'gym-2003',
    authDomain: 'gym-2003.firebaseapp.com',
    storageBucket: 'gym-2003.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEitNsALOt3l6uo9ge_O5Ae8wem4muD7g',
    appId: '1:91000484395:android:d7b330874316f7a235b06e',
    messagingSenderId: '91000484395',
    projectId: 'gym-2003',
    storageBucket: 'gym-2003.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvKJogiafIESGEzAsZShUZAd81Gs2MCJU',
    appId: '1:91000484395:ios:2926f1921d7911b535b06e',
    messagingSenderId: '91000484395',
    projectId: 'gym-2003',
    storageBucket: 'gym-2003.firebasestorage.app',
    iosBundleId: 'com.example.gymApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvKJogiafIESGEzAsZShUZAd81Gs2MCJU',
    appId: '1:91000484395:ios:2926f1921d7911b535b06e',
    messagingSenderId: '91000484395',
    projectId: 'gym-2003',
    storageBucket: 'gym-2003.firebasestorage.app',
    iosBundleId: 'com.example.gymApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXaJkK6lxmGuy2G6iaR-n0LbdaT7Jt2l0',
    appId: '1:91000484395:web:0d2aee6965f5d83135b06e',
    messagingSenderId: '91000484395',
    projectId: 'gym-2003',
    authDomain: 'gym-2003.firebaseapp.com',
    storageBucket: 'gym-2003.firebasestorage.app',
  );
}
